/** Evening mantras — recovery, release, reflection (30+ per locale). */

module.exports = {
  en: [
    "Recovery is discipline too.",
    "Silence restores clarity.",
    "Rest without guilt.",
    "The body remembers pressure.",
    "Lower the noise tonight.",
    "You do not need to solve everything tonight.",
    "Evening favors release over review.",
    "Screens down. Mind down.",
    "One honest line about today.",
    "Sleep protects tomorrow's edge.",
    "Pressure off. Standards stay.",
    "Recovery is active, not passive.",
    "Let the unfinished wait.",
    "Calm the nervous system before the list.",
    "Reflection without rumination.",
    "Downshift is part of the path.",
    "The day closes — your worth does not.",
    "Gentle close beats late heroics.",
    "Quiet input after dark.",
    "Breath longer than the day required.",
    "Tomorrow starts with rest tonight.",
    "Evening discipline: stop on time.",
    "Honor fatigue without shame.",
    "One moment of stillness.",
    "Release what you cannot finish.",
    "The night is for repair.",
    "Lower stimulation, not ambition forever.",
    "What strengthened you today?",
    "Protect sleep like training.",
    "Evening mantra: enough for today.",
    "Close the body before the mind argues.",
    "Recovery protects the next push."
  ],
  hu: [
    "A felépülés is fegyelem.",
    "A csend visszaadja a tisztánlátást.",
    "Pihenés bűntudat nélkül.",
    "A test emlékszik a nyomásra.",
    "Csökkentsd a zajt ma éjjel.",
    "Nem kell ma mindent megoldanod.",
    "Az este az elengedést részesíti előnyben.",
    "Képernyő le. Elme le.",
    "Egy őszinte sor a mai napról.",
    "Az alvás védi a holnapi élt.",
    "Nyomás le. A standard marad.",
    "A felépülés aktív, nem passzív.",
    "A befejezetlen várhat.",
    "Nyugtasd az idegrendszert a lista előtt.",
    "Reflexió rumináció nélkül.",
    "A lefelé is része az útnak.",
    "A nap zár — az értéked nem.",
    "Finom zárás jobb, mint késői hősködés.",
    "Csendes input sötétben.",
    "Lélegezz hosszabban, mint a nap kért.",
    "A holnap ma éjjeli pihenéssel indul.",
    "Esti fegyelem: időben stop.",
    "Tiszteld a fáradtságot szégyen nélkül.",
    "Egy pillanat csend.",
    "Engedd el, amit nem zársz ma.",
    "Az éjszaka a javításé.",
    "Kevesebb stimuláció, nem örökre kevesebb ambíció.",
    "Mi erősített ma?",
    "Védd az alvást, mint az edzést.",
    "Esti mantra: elég mára.",
    "Zárd a testet, mielőtt a fej vitatkozik.",
    "A felépülés védi a következő push-t."
  ],
  ro: [
    "Recuperarea e disciplină.",
    "Liniștea restabilește claritatea.",
    "Odihnă fără vinovăție.",
    "Corpul își amintește presiunea.",
    "Reduce zgomotul diseară.",
    "Nu trebuie să rezolvi totul diseară.",
    "Seara favorizează eliberarea.",
    "Ecrane jos. Minte jos.",
    "O linie onestă despre azi.",
    "Somnul protejează muchia de mâine.",
    "Presiune jos. Standardul rămâne.",
    "Recuperarea e activă.",
    "Nefinisitul poate aștepta.",
    "Calmează sistemul nervos înainte de listă.",
    "Reflexie fără ruminație.",
    "Coborârea face parte din drum.",
    "Ziua se închide — valoarea ta nu.",
    "Închidere blândă bate eroismul târziu.",
    "Input liniștit după întuneric.",
    "Respirație mai lungă decât a cerut ziua.",
    "Mâine începe cu odihna de diseară.",
    "Disciplină de seară: stop la timp.",
    "Onorează oboseala fără rușine.",
    "Un moment de liniște.",
    "Eliberează ce nu poți închide azi.",
    "Noaptea e pentru reparare.",
    "Mai puțină stimulare, nu mai puțină ambiție pentru totdeauna.",
    "Ce te-a întărit azi?",
    "Protejează somnul ca antrenamentul.",
    "Mantra seară: destul pentru azi.",
    "Închide corpul înainte să argumenteze mintea.",
    "Recuperarea protejează următorul push."
  ]
};
