/** Midday mantras — correction, stabilization, focus (30+ per locale). */

module.exports = {
  en: [
    "Protect your attention.",
    "One task. One lane.",
    "Slow is still movement.",
    "Reduce unnecessary stimulation.",
    "Refocus and continue.",
    "Midday is a correction, not a restart.",
    "Do not leak energy into noise.",
    "Return to the open loop.",
    "Breathe slower than the pace you want.",
    "One execution block left.",
    "Stabilize before you scale.",
    "The middle of the day needs guardrails.",
    "Close the distraction, not the ambition.",
    "Nervous system before new tasks.",
    "Hydrate. Posture. Continue.",
    "Anti-chaos: one visible finish.",
    "Drift is expensive — recenter.",
    "Half-day discipline check.",
    "Keep the lane narrow.",
    "Attention is finite — spend it deliberately.",
    "Pause is not failure.",
    "Reduce scope, keep standard.",
    "Midday favors continuation over expansion.",
    "One correction beats ten new plans.",
    "Calm jaw. Slow exhale. Resume.",
    "Do not negotiate with scatter.",
    "Execute the next line, not the whole map.",
    "Stimulation down. Focus up.",
    "The task in front of you is enough.",
    "Regulate, then push.",
    "Midday mantra: one lane, one finish.",
    "Protect the rhythm you built this morning."
  ],
  hu: [
    "Védd a figyelmed.",
    "Egy feladat. Egy sáv.",
    "A lassú is mozgás.",
    "Csökkentsd a felesleges stimulációt.",
    "Fókusz vissza, folytasd.",
    "A dél korrekció, nem újrakezdés.",
    "Ne szivárogjon az energia a zajba.",
    "Vissza a nyitott körhöz.",
    "Lélegezz lassabban, mint amit akarsz.",
    "Egy végrehajtási blokk maradt.",
    "Stabilizálj, mielőtt skálázol.",
    "A nap közepe kerítést kér.",
    "Zárd a zavarót, ne az ambíciót.",
    "Idegrendszer az új taskok előtt.",
    "Víz. Testtartás. Folytasd.",
    "Anti-káosz: egy látható befejezés.",
    "A sodródás drága — vissza középre.",
    "Fél napos fegyelem-ellenőrzés.",
    "Tartsd szűken a sávot.",
    "A figyelem véges — szándékosan költsd.",
    "A szünet nem bukás.",
    "Csökkentsd a scope-ot, tartsd a standardot.",
    "A dél a folytatást részesíti előnyben.",
    "Egy korrekció jobb, mint tíz új terv.",
    "Laza állkapocs. Lassú kilélegzés. Folytasd.",
    "Ne alkudozz a szétszórással.",
    "A következő sort futtasd, ne az egész térképet.",
    "Stimuláció le. Fókusz fel.",
    "Az előtted lévő feladat elég.",
    "Regulálj, aztán nyomás.",
    "Déli mantra: egy sáv, egy finish.",
    "Védd a reggel épített ritmusát."
  ],
  ro: [
    "Protejează atenția.",
    "Un task. O bandă.",
    "Lent e tot mișcare.",
    "Reduce stimularea inutilă.",
    "Refocusează și continuă.",
    "Prânzul e corecție, nu restart.",
    "Nu pierde energia în zgomot.",
    "Înapoi la cercul deschis.",
    "Respiră mai lent decât ritmul dorit.",
    "Un bloc de execuție rămas.",
    "Stabilizează înainte să scalezi.",
    "Mijlocul zilei are nevoie de garduri.",
    "Închide distracția, nu ambiția.",
    "Sistem nervos înainte de taskuri noi.",
    "Apă. Postură. Continuă.",
    "Anti-haos: un finish vizibil.",
    "Driftul e scump — recentrează.",
    "Check disciplină la jumătatea zilei.",
    "Ține banda îngustă.",
    "Atenția e finită — cheltuiește deliberat.",
    "Pauza nu e eșec.",
    "Reduce scope, păstrează standardul.",
    "Prânzul favorizează continuarea.",
    "O corecție bate zece planuri noi.",
    "Maxilar relaxat. Expirație lentă. Reia.",
    "Nu negocia cu scatter-ul.",
    "Execută linia următoare, nu harta.",
    "Stimulare jos. Focus sus.",
    "Taskul din față e suficient.",
    "Reglează, apoi împinge.",
    "Mantra prânz: o bandă, un finish.",
    "Protejează ritmul construit dimineața."
  ]
};
