/** Morning mantras — activation, focus, discipline, movement (30+ per locale). */

module.exports = {
  en: [
    "Protect the first hour.",
    "One direction is enough.",
    "Move before motivation.",
    "Attention is energy.",
    "Hydrate. Breathe. Begin.",
    "Clarity before intensity.",
    "Start slow. Start true.",
    "The first block sets the day.",
    "Discipline at dawn, not drama.",
    "One lane until noon.",
    "Body awake before the feed.",
    "Water before stimulation.",
    "Direction before noise.",
    "Stand up. One breath. Begin.",
    "Focus is a physical act.",
    "No heroics — one honest start.",
    "Protect attention like fuel.",
    "Movement unlocks the mind.",
    "One commitment visible.",
    "Structure beats mood this morning.",
    "Calm entry, clean exit from bed.",
    "The morning is a gate, not a sprint.",
    "Hydration is the first discipline.",
    "One target. No side quests.",
    "Breathe in. Choose one line of work.",
    "Activation without overstimulation.",
    "First hour: low input, high intent.",
    "Walk before scroll.",
    "Anchor the nervous system, then plan.",
    "Today begins with one clean action.",
    "Morning favors clarity over volume.",
    "Begin with the body, then the task."
  ],
  hu: [
    "Védd az első órát.",
    "Egy irány elég.",
    "Mozgás a motiváció előtt.",
    "A figyelem energia.",
    "Hidratálás. Légzés. Kezdés.",
    "Tisztánlátás az intenzitás előtt.",
    "Lassan indulj. Őszintén.",
    "Az első blokk adja a napot.",
    "Fegyelem hajnalban, nem dráma.",
    "Egy sáv délig.",
    "Test ébren a feed előtt.",
    "Víz stimuláció előtt.",
    "Irány a zaj előtt.",
    "Állj fel. Egy lélegzet. Kezdés.",
    "A fókusz fizikai cselekvés.",
    "Nincs hősködés — őszinte start.",
    "Védd a figyelmet, mint az üzemanyagot.",
    "A mozgás nyitja a fejet.",
    "Egy látható ígéret.",
    "Szerkezet legyőzi a hangulatot reggel.",
    "Nyugodt belépés, tiszta felkelés.",
    "A reggel kapu, nem sprint.",
    "A hidratálás az első fegyelem.",
    "Egy cél. Nincs mellékküldetés.",
    "Belélegzés. Egy munkasor.",
    "Aktiválás túlstimuláció nélkül.",
    "Első óra: kevés input, erős szándék.",
    "Séta scroll előtt.",
    "Horgony az idegrendszernek, aztán terv.",
    "A nap egy tiszta cselekvéssel indul.",
    "A reggel a tisztánlátást részesíti előnyben.",
    "Testtel kezd, aztán a feladat."
  ],
  ro: [
    "Protejează prima oră.",
    "O direcție e suficient.",
    "Mișcă înainte de motivație.",
    "Atenția e energie.",
    "Hidratează. Respiră. Începe.",
    "Claritate înainte de intensitate.",
    "Începe lent. Sincer.",
    "Primul bloc setează ziua.",
    "Disciplină la răsărit, nu dramă.",
    "O bandă până la prânz.",
    "Corp trez înainte de feed.",
    "Apă înainte de stimulare.",
    "Direcție înainte de zgomot.",
    "Ridică-te. O respirație. Începe.",
    "Focusul e act fizic.",
    "Fără eroism — start onest.",
    "Protejează atenția ca pe combustibil.",
    "Mișcarea deschide mintea.",
    "Un angajament vizibil.",
    "Structura bate starea dimineața.",
    "Intrare calmă, trezire curată.",
    "Dimineața e poartă, nu sprint.",
    "Hidratarea e prima disciplină.",
    "O țintă. Fără side quest-uri.",
    "Inspirație. Alege o linie de lucru.",
    "Activare fără suprastimulare.",
    "Prima oră: input mic, intenție mare.",
    "Mers înainte de scroll.",
    "Ancorează sistemul nervos, apoi planul.",
    "Ziua începe cu o acțiune curată.",
    "Dimineața favorizează claritatea.",
    "Începe cu corpul, apoi taskul."
  ]
};
